services:
  mysql:
    image: mysql:8.3.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: 'Asia/Shanghai'
    ports:
      - 3306:3306
volumes:
  mysql:
